feat: animations done
LOFyz/super-castlevania-4-tcc-cocos pull request #12
Opened 2021-05-18 21:11 UTC by LOFyz

2021-05-18 22:56 UTC, Manuel-Antunes commented
Preciso das prints

2021-05-18 23:50 UTC, LOFyz commented
![Animação](https://user-images.githubusercontent.com/75549646/118737170-a9102480-b81a-11eb-82cc-9f7fded0ab70.gif)

2021-05-19 16:46 UTC, Manuel-Antunes requested changes
Diminua o framehate dessas animações pra 30 e aumente a velocidade
do jeito que está tá mt bugado

2021-05-19 22:05 UTC, LOFyz commented
![Animação](https://user-images.githubusercontent.com/75549646/118890495-2ac48880-b8d5-11eb-81b7-37cfc5f86088.gif)

2021-05-20 02:21 UTC, Manuel-Antunes approved these changes

2021-05-20 02:41 UTC, merged