Create map
LOFyz/super-castlevania-4-tcc-cocos pull request #19
Opened 2021-05-22 23:18 UTC by LOFyz

I first added the map assets
![image](https://user-images.githubusercontent.com/75549646/119243155-aa9f5c80-bb3a-11eb-9369-701c00dc2c64.png)
Then I positioned the assets in the scene
![image](https://user-images.githubusercontent.com/75549646/119243168-cb67b200-bb3a-11eb-942c-7e645304400e.png)
I needed to split some assets, to make colisions in the future

2021-05-22 23:54 UTC, LOFyz commented
I added colision to the nodes in the scene

2021-05-23 00:29 UTC, LOFyz commented
I started to code the bridge platform block. I created a state variable, which by being at the true value for 3 seconds, makes the platform suffer the effect of gravity that will be added later.

2021-05-23 01:07 UTC, LOFyz commented
The animation of the block bridge platform
![Animação](https://user-images.githubusercontent.com/75549646/119244756-0de4bb00-bb4a-11eb-932e-a4d207d31e21.gif)

2021-05-23 14:11 UTC, Manuel-Antunes requested changes
favor corrija essas alterações.

2021-05-23 14:11 UTC, Manuel-Antunes commented on assets/scripts/Map/Bridge/blockPlatform.ts
> +/* eslint-disable @typescript-eslint/no-unused-vars */
```suggestion

```
Remova essas duas linhas

2021-05-23 14:11 UTC, Manuel-Antunes commented on assets/scripts/Map/Bridge/blockPlatform.ts
> +const { ccclass, property } = cc._decorator;
```suggestion
const { ccclass } = cc._decorator;
```
O property não está sendo usado pra nada, remova-o

2021-05-23 14:11 UTC, Manuel-Antunes commented on assets/scripts/Map/Bridge/blockPlatform.ts
> +export default class blockPlatform extends cc.Component {
NOME DE CLASSE COM LETRA MINÚSICA LÉO ?

2021-05-23 14:11 UTC, Manuel-Antunes commented on assets/scripts/Map/Bridge/blockPlatform.ts
> +  public onBeginContact(_contact: Event, _selfCollider: cc.BoxCollider, _otherCollider: cc.BoxCollider): void {
Essas variáveis não estão sendo usadas, e não são obrigatórias, coloque apenas as que vai usar, e caso precise de uma mais a frente, insira um _nomeDaVariavel no lugar do nome, para mostrar que ela é inútil.

2021-05-23 14:11 UTC, Manuel-Antunes commented on assets/scripts/Map/Bridge/blockPlatform.ts
> +        this.getComponent(cc.Animation).play('bridge_block_platform');
A lógica geral dessa função não faz sentido, favor corrigir.

2021-05-25 22:33 UTC, Manuel-Antunes approved these changes
belo penis

2021-05-26 22:48 UTC, merged