Feat-Chore: function to make character jump is done, and the reface f…
LOFyz/super-castlevania-4-tcc-cocos pull request #22
Opened 2021-05-28 23:22 UTC by LOFyz

…unction.

2021-05-29 03:34 UTC, Manuel-Antunes commented on assets/scripts/Actor/Main_Character/MainCharacter.ts
> +  public refacing(direction: DIRECTION): void {
```suggestion
  public reface(direction: DIRECTION): void {
```
pfv corrija "refacing" parece mais nome de propriedade que de função.

2021-05-29 03:39 UTC, Manuel-Antunes requested changes
Corrija os pontos por favor.

2021-05-29 03:39 UTC, Manuel-Antunes commented on assets/scripts/Actor/Main_Character/MainCharacter.ts
> +      this.scheduleOnce(() => {
Tratar de estados de animação das coisas deve ser trabalho da state machine

2021-05-29 03:39 UTC, Manuel-Antunes commented on assets/scripts/Controller/main_character/MainCharacterController.ts
> +        delete this.keysPressed['JUMP'];
?

2021-05-29 09:44 UTC, LOFyz commented on assets/scripts/Controller/main_character/MainCharacterController.ts
> +        delete this.keysPressed['JUMP'];
O personagem não tava pulando enquanto andava, testei isso, mas deu na mesma. Esqueci de mudar

2021-05-29 12:37 UTC, Manuel-Antunes requested changes
Fazer o merge com a branch da ultima pull request e tentar novamente

2021-06-05 18:03 UTC, Manuel-Antunes approved these changes
corrija aquela alteração e pronto

2021-06-05 18:03 UTC, Manuel-Antunes commented on assets/scripts/Actor/Actor.ts
> +    return !this.isJumping;
Coloque a parada da linear velocity de volta
```suggestion
    return this.rigidBody.linearVelocity.y !== 0 && !this.isJumping;
```

2021-06-05 18:17 UTC, merged