make-transition-player-animations
LOFyz/super-castlevania-4-tcc-cocos pull request #23
Opened 2021-06-01 21:04 UTC by LOFyz

2021-06-01 21:15 UTC, LOFyz commented
![Animação](https://user-images.githubusercontent.com/75549646/120391429-6283f500-c305-11eb-8835-370837f4fe36.gif)

2021-06-02 10:17 UTC, Manuel-Antunes requested changes
Corrija os pontos citados.

2021-06-02 10:17 UTC, Manuel-Antunes commented on assets/scripts/Actor/Actor.ts
> +    return this._isJumping;
Essa parada aqui tá inútil

2021-06-02 10:17 UTC, Manuel-Antunes commented on assets/scripts/Actor/Actor.ts
> +  public rigidBody: cc.RigidBody;
```suggestion
  protected rigidBody: cc.RigidBody;
```
se tiver que acessar métodos dessa propriedade de forma externa, crie funções públicas internas à classe, pq provavelmente vai ter reutilização

2021-06-02 10:17 UTC, Manuel-Antunes commented on assets/scripts/Actor/Main_Character/MainCharacter.ts
> +    return this.direction !== 0;
Eu n tô gostando dessa parada de usar variável de direção pra pegar se o cara tá andando, n sei... me convença.

2021-06-02 10:17 UTC, Manuel-Antunes commented on assets/scripts/Actor/Main_Character/PlayerStateMachine.ts
> +/* eslint-disable @typescript-eslint/no-empty-function */
```suggestion
```

2021-06-02 10:17 UTC, Manuel-Antunes commented on assets/scripts/Actor/Main_Character/PlayerStateMachine.ts
> +  public onAnimationStart(): void {}
nem que seja um console.log coloque algo aqui, o eslint existe por um motivo :D

2021-06-03 21:26 UTC, LOFyz commented on assets/scripts/Actor/Main_Character/MainCharacter.ts
> +    return this.direction !== 0;
Ele não desliza bixo, para instantaneamente. Então, essa é a melhor forma de conseguir esse estado, pois é instantaneo.

2021-06-05 18:05 UTC, Manuel-Antunes approved these changes
Belo penis

2021-06-05 18:17 UTC, merged