make-camera
LOFyz/super-castlevania-4-tcc-cocos pull request #25
Opened 2021-06-01 22:00 UTC by LOFyz

2021-06-02 10:06 UTC, Manuel-Antunes commented
Providencie os GIFs do funcionamento

2021-06-02 10:22 UTC, Manuel-Antunes requested changes
Mandar GIFs para uma próxima revisão.

2021-06-02 10:22 UTC, Manuel-Antunes commented on assets/scripts/Camera/Camera.ts
> +    this.limits[0] = this.node.parent.convertToWorldSpaceAR(this.map.getPosition()).x;
Lógica interessante, manda o GIF pra eu ver como funciona

2021-06-02 10:22 UTC, Manuel-Antunes commented on assets/scripts/Map/Bridge/BlockPlatform.ts
> +    this.getComponent(cc.Animation).play('bridge_block_platform');
?
wtf, manda o GIF disso tbm

2021-06-03 21:41 UTC, LOFyz commented on assets/scripts/Map/Bridge/BlockPlatform.ts
> +    this.getComponent(cc.Animation).play('bridge_block_platform');
Eu só consegui testar isso melhor agora que a camera mexe. Vou mostrar os dois no gif

2021-06-03 22:34 UTC, LOFyz commented
https://user-images.githubusercontent.com/75549646/120720479-8597db80-c4a2-11eb-92af-0382f6dda39b.mp4

2021-06-05 18:07 UTC, Manuel-Antunes approved these changes

2021-06-05 18:17 UTC, merged